version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: tabla de los productos de greenweez
        columns:
          - name: products_id
            description: ID del producto
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: precio de compra al consumidor
      - name: sales
        identifier: raw_gz_sales
        description: tabla de ventas de greenweez
        columns:
          - name: date_date
            description: fecha de cuando se realizo la venta 
          - name: orders_id
            description: ID de la orden
          - name: pdt_id
            description: ID del producto 
          - name: revenue
            description: monto de ingreso
          - name: quantity
            description: cantidad vendida
        tests:
          - unique:
              column_name: "(date_date || '-' || orders_id || '-' ||pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: tabla de los costos de envío por orden en greenweez
        columns:
          - name: orders_id
            description: ID de la orden
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: Monto de costo del envío
          - name: logCost
            description: costo logístico de la orden
          - name: ship_cost
            description: costo del trasporte a destinno de la orden

models:
   - name: int_sales_margin
     description: margin calculation per order
     columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: products_id
         description: products key
         tests:
           - not_null
       - name: margin
         description: Margin = Revenue - Purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: Purchase_cost = Quantity * Purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
     tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"
   - name: int_orders_margin
     description: margin calculation per order
     columns:
       - name: orders_id
         description: primary key
         tests:
           - unique
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: purchase_cost = quantity * purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null

   - name: int_sales_margin
     description: margin calculation per order line / product sales
     columns:
       - name: orders_id
         description: orders key
         tests:
           - not_null
       - name: products_id
         description: products key
         tests:
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: Purchase_cost
         description: purchase_cost = quantity * purchase_price
         tests:
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
     tests:
       - unique:
           column_name: "(orders_id || '-' || products_id)"

   - name: int_orders_operational
     description: operational margin calculation per order
     columns:
       - name: orders_id
         description: primary key
         tests:
           - unique
           - not_null
       - name: date_date
         description: date of the order
         tests:
           - not_null
       - name: operational_margin
         description: operational_margin = margin + shipping_fee - logcost - ship_cost
       - name: quantity
         description: sum of quantity per order
         tests:
           - not_null
       - name: revenue
         description: sum of revenue per order
         tests:
           - not_null
       - name: purchase_cost
         description: purchase_cost = quantity * purchase_price
         tests:
           - not_null
       - name: margin
         description: margin = revenue - purchase_cost
         tests:
           - not_null
       - name: shipping_fee
         description: the price the customer pays for shipping
       - name: logcost
         description: the cost of preparing the parcel in the distribution centre/warehouse
       - name: ship_cost
         description: shipping cost paid by Greenweez to the carrier/logistics provider
                     